# For more information: https://laravel.com/docs/sail
version: '3'
services:
  portfolio_app_container:
    build:
      context: ./runtimes/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.1/app
    container_name: portfolio_app_container
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-8085}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - '.:/var/www/html'
    networks:
      - portfolio_container_network
    depends_on:
      - portfolio_mysql_container
  portfolio_mysql_container:
    image: 'mysql/mysql-server:8.0'
    container_name: portfolio_mysql_container
    ports:
      - '${FORWARD_DB_PORT:-3318}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'portfolio-mysql:/var/lib/mysql'
    networks:
      - portfolio_container_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  redis_portfolio_container:
    image: 'redis:alpine'
    container_name: redis_portfolio_container
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis_portfolio_volume:/data'
    networks:
      - portfolio_container_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  portfolio_container_network:
    driver: bridge
volumes:
  portfolio-mysql:
    driver: local
  redis_portfolio_volume:
    driver: local
